# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameLovers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GameLovers
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 4.6'
  pod 'UIScrollView-InfiniteScroll', '~> 1.0'

  target 'GameLoversTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GameLoversUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
